name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - neslang-05

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission checklist
      description: Please check the following items before submitting
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have read the documentation
          required: true
        - label: I can reproduce this bug consistently
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs to help explain your problem.
      placeholder: Paste error logs here...
      render: shell

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected by this bug?
      options:
        - AI/ML Engine
        - Chat Interface
        - Dashboard
        - API Backend
        - Authentication
        - Database
        - Docker/Deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (minor issue)
        - Medium (affects functionality)
        - High (major functionality broken)
        - Critical (system unusable)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      placeholder: v1.0.0 or commit hash

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: In what environment did this bug occur?
      options:
        - Development (local)
        - Docker container
        - Cloud deployment (Vercel)
        - Cloud deployment (Railway)
        - Cloud deployment (Render)
        - Other

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Please provide your system information
      placeholder: |
        OS: [e.g., Windows 11, macOS 13, Ubuntu 22.04]
        Browser: [e.g., Chrome 118, Firefox 119]
        Python version: [e.g., 3.9.7]
        Node.js version: [e.g., 18.17.0]

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.