name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees:
  - neslang-05

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please fill out this form as completely as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission checklist
      description: Please check the following items before submitting
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature would benefit other users, not just me
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternatively, we could...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this feature request affect?
      options:
        - AI/ML Engine
        - Chat Interface
        - Dashboard
        - API Backend
        - Authentication
        - Database
        - Documentation
        - DevOps/Deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would be helpful)
        - High (important for my use case)
        - Critical (blocking my usage)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to help implement this feature
        - label: I can provide testing and feedback
        - label: I can help with documentation